data_provider:
  root: /home/infres/vnguyen-23/dataset/vww
  num_classes: 2

run_config:
  # learning rate
  bs256_lr: 0.01
  # optimizer
  optimizer_name: sgd

net_config:
  net_name: mbv2-w0.35
  gradfilt: 1
  radius: 2
  num_of_conv_finetune: 2
  quantized: 1